# Generated by Django 4.1.1 on 2022-10-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('rota_id', models.IntegerField(primary_key=True, serialize=False)),
                ('outro_aeroporto', models.CharField(max_length=50)),
                ('chegada', models.BooleanField()),
            ],
            options={
                'db_table': 'rota',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'voo',
            },
        ),
        migrations.CreateModel(
            name='ProgressoVoo',
            fields=[
                ('progresso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'progressoVoo',
            },
        ),
    ]
