# Generated by Django 4.1.2 on 2022-10-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressoVoo',
        ),
    ]
