# Generated by Django 4.1.1 on 2022-10-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_delete_progressovoo_delete_status_delete_voo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('voo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('companhia_aerea', models.CharField(max_length=255)),
                ('horario_partida_previsto', models.DateTimeField()),
                ('horario_chegada_previsto', models.DateTimeField()),
                ('rota_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.rota')),
            ],
            options={
                'db_table': 'voo',
            },
        ),
    ]
