# Generated by Django 4.1.2 on 2022-10-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_progressovoo'),
        ('book', '0004_status_progressovoo'),
    ]

    operations = [
    ]
