# Generated by Django 4.1.2 on 2022-10-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_merge_0003_progressovoo_0004_status_progressovoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressovoo',
            name='status_voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.status'),
        ),
    ]
