# Generated by Django 4.1.2 on 2022-10-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_progressovoo_status_voo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MudancaEstado',
            fields=[
                ('mudancaestado_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('proximoestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'mudancaEstado',
            },
        ),
    ]
