# Generated by Django 4.1.2 on 2022-10-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_mudancaestado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MudancaEstado',
        ),
    ]
