# Generated by Django 4.1.2 on 2022-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_delete_mudancaestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressovoo',
            name='progresso_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rota',
            name='rota_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voo',
            name='voo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
