# Generated by Django 4.1.2 on 2022-11-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_progressovoo_progresso_id_alter_rota_rota_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo',
            old_name='horario_chegada_previsto',
            new_name='horario_previsto',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='horario_partida_previsto',
        ),
    ]
